server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university-lc
    username: donik_admin
    password: 123654789.Doniyorrrtg
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

upload:
  folder: UFTU-Lc/public
